### ISSUE TITLE
Text changes unorderly on deleting input value

### ISSUE THREAD

**Issue by shubhamV123** [msudgh/react-email-autocomplete#11]
When you try to delete certain domains once its completed or try to delete from the last keyword. Input value delete random input keyword.

![react-autocomplete 2019-07-20 00_26_36](https://user-images.githubusercontent.com/29898106/61558639-40708900-aa85-11e9-85d6-35b96e3d56d3.gif)

Here is the list in which it's not working properly : 

- gmail.com,
- googlemail.com,
- me.com,
- mac.com,
- msn.com,
- hotmail.com,
- verizon.net,
- rediffmail.com,
- mail.com,
- protonmail.com

**Comment by shubhamV123** [comment]
Found the issue, what happens in **getSuggest** function is it replacing the input value(deleted keyword) with an empty string, but javascript replace work like it replaces the first occurrence of the keyword. So when I try to delete **m** from last it deletes first occurrence **m** from the input value. 
Here is the fix: #12

**Comment by shubhamV123** [comment]
@msudgh I have closed this issue. Feel free to open this issue. If you found any bug.

**Comment by msudgh** [comment]
@shubhamV123 Sure why not
