### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by yocmen** [msudgh/react-email-autocomplete#25]
Hi, the demo page is not working, on console you can see the message `ReferenceError: useEffect is not defined`

**Comment by msudgh** [comment]
Thanks to reach out. V1.2.3 mistakenly released.
Beta changes excluded from `master` branch with released version [1.3.3](https://github.com/msudgh/react-email-autocomplete/releases/tag/v1.3.3)

**Comment by yocmen** [comment]
Hi, i see now the demo page is working, but in my project got the same error too, maybe is a related thing?

**Comment by msudgh** [comment]
Please make sure the latest version is installed.

```
npm i react-email-autocomplete@latest --save
```

**Comment by yocmen** [comment]
Yes, I have the last version I think, maybe its because it needs a reference for the useEffect.

```import React, { useState, useRef } from 'react';```

to 

```import React, { useState, useRef, useEffect } from 'react';```

on the /src/index.js file.

**Comment by masoudgs** [comment]
@yocmen Yes. I fixed the issue but reverted changes was missing.
Would you please try again with installing latest version?

**Comment by yocmen** [comment]
Done, is properly working now, really thanks.
