### ISSUE TITLE
Would be great to have a link to demo

### ISSUE THREAD

**Issue by vfonic** [msudgh/react-email-autocomplete#3]
Hey,

Just saw this package in React newsletter and came to check what's it all about. I wish there would be a demo to show how it works/looks like.

I eventually found the demo for the jQuery plugin so now I understand how it works, but it would still be great if this repo had a demo of its own.

Thanks!

**Comment by msudgh** [comment]
Thanks for your great idea, we can have a demo page. I'll work on it.
Also, PRs are welcome.
